
services:
  checker_tcp:
    container_name: server
    build: .
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    environment:
      SERVER_ADDRESS: "${SERVER_ADDRESS:-0.0.0.0}"
      SERVER_PORT: "${SERVER_PORT:-8080}"
      SERVER_READ_TIMEOUT: "${SERVER_READ_TIMEOUT:-30s}"
      SERVER_IDLE_TIMEOUT: "${SERVER_IDLE_TIMEOUT:-30s}"
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
